name: Review Requested

on:
  pull_request:
    types: [review_requested]
jobs:
  send-mattermost-message:
    runs-on: ubuntu-latest
    steps:
    - uses: mattermost/action-mattermost-notify@master
      with:
        MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_ASSIGN_WEBHOOK }}
        MATTERMOST_USERNAME: ${{ github.actor }}
        MATTERMOST_ICON_URL: https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png
        TEXT: >
            Review requested from ${{ github.event.requested_reviewer.login }} for "${{ github.event.pull_request.title }}": ${{ github.event.pull_request.html_url }}
