name: Tox steps
on:
  workflow_call:
    inputs:
      PYTHON_VERSION:
        type: string
      IMAGE_NAME:
        type: string
      TOXENV:
        type: string
      PIP_USE_PEP517:
        type: string
    secrets:
      AWS_TEST_FARM_PEM:
        required: false
      AWS_ACCESS_KEY_ID:
        required: false
      AWS_SECRET_ACCESS_KEY:
        required: false

permissions:
  contents: read

jobs:
  tox_all:
    name: ${{ inputs.TOXENV }} ${{ inputs.IMAGE_NAME }}
    runs-on:
      - "${{ inputs.IMAGE_NAME }}"
    env:
      AWS_EC2_PEM_FILE: ${{ github.workspace }}/GHAKeyPair.pem
    steps:
    - run: echo "yay :)"
      shell: bash
      name: run a test!
